name: Build-and-Test-CLANG

on:
  push:
    branches:
    - main
    - dev

jobs:
  Build:
    runs-on: macos-latest
    
    strategy:
      fail-fast: false
      matrix:
        clang: [17]
        build_type: [Debug, Release]
        std: [20]

    steps:
    - uses: actions/checkout@v3

    - name: Install Clang17
      run: |
            brew install llvm
            echo 'export PATH="/usr/local/opt/llvm/bin:$PATH"' >> ~/.bash_profile

    - name: Configure CMake
      working-directory: Tests
      run: |
           cmake -S . -B ./Build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_CXX_COMPILER=/usr/local/opt/llvm/bin/clang-16 -DGITHUB_BRANCH_TYPE=${{github.ref}}

    - name: Build the Test
      working-directory: Tests/Build
      run: |
           cmake --build . --config=${{matrix.build_type}}

    - name: Run the Test
      working-directory: Tests/Build
      run: |
           ./Json-Performance
      