name: Build-and-Test-MSVC

on:
  push:
    branches:
    - main
    - dev

jobs:
  Build:
    runs-on: windows-2022
    
    strategy:
      fail-fast: false
      matrix:
        msvc: [2022]
        build_type: [Debug, Release]
        std: [20]

    steps:
    - uses: actions/checkout@v3
      
    - name: Append the directory of 'vcvarsall.bat' to PATH environment variable
      uses: myci-actions/export-env-var-powershell@1
      with:
         name: PATH
         value: $env:PATH;C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build

    - name: Configure CMake
      working-directory: Tests
      run: |
           cmake -S . -B ./Build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DGITHUB_BRANCH_TYPE=${{github.ref}}

    - name: Build the Test
      working-directory: Tests/Build
      run: |
           cmake --build . --config=${{matrix.build_type}}

    - name: Run the Test
      working-directory: Tests/Build/${{matrix.build_type}}/
      run: |
           ./Json-Performance.exe
  